create table role (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email varchar(255), name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references role (id);
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references user (id);
insert into role (name) values ("ROLE_USER");
insert into role (name) values ("ROLE_ADMIN");
select role0_.id as id1_0_, role0_.name as name2_0_ from role role0_ where role0_.name="ROLE_USER";
insert into user (email, name, last_name, password) values ("user", "user", "user@gmail.com", "user");
insert into users_roles (user_id, role_id) values (1, 1);
select role0_.id as id1_0_, role0_.name as name2_0_ from role role0_ where role0_.name="ROLE_ADMIN";
insert into user (email, name, last_name, password) values ("admin", "admin", "admin@gmail.com", "admin");
insert into users_roles (user_id, role_id) values (2, 2);
select role0_.id as id1_0_, role0_.name as name2_0_ from role role0_ where role0_.name="ROLE_USER";
select role0_.id as id1_0_, role0_.name as name2_0_ from role role0_ where role0_.name="ROLE_ADMIN";
insert into user (email, name, last_name, password) values ("both", "both", "both@gmail.com", "both@gmail.com");
insert into users_roles (user_id, role_id) values (3, 1);
insert into users_roles (user_id, role_id) values (3, 2);
